name: gtest tests

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up CMake
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential libgtest-dev

      # Build the project and tests
      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      # Run tests
      - name: Run tests
        run: ./build/test_exe
