name: test performance on github actions
on: [push]

jobs:
    test_main:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run main script
            run: g++ main.cpp -o main; ./main
    test_dataset:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run test script
            run: g++ test_dataset.cpp -o test_dataset; ./test_dataset

    test_baruch_dataset:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run test script on dataset from Baruch
            run: g++ test_dataset.cpp -o test_dataset; ./test_dataset parse_baruch_dataset/data

    test_performance:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run performance script
            run: g++ test_performance.cpp -o test_performance; ./test_performance

    test_rejection:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: test with rejection
            run: g++ -g test_dataset_with_rejection.cpp; ./a.out data_rejection
