name: Test Performance on GitHub Actions

on: [push]

jobs:
  # General build and test job
  build_and_test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run All Tests with CTest
        run: |
          cd build
          ctest -V

  # Run main executable
  test_main:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run Main Script
        run: |
          cd build
          ./src/main

  # Run dataset test
  test_dataset:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run Dataset Test
        run: |
          cd build
          ./src/test_dataset

  # Run dataset with rejection test
  test_rejection:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run Rejection Test
        run: |
          cd build
          ./src/test_dataset_with_rejection datasets/data_rejection

  # Run performance test
  test_performance:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run Performance Test
        run: |
          cd build
          ./src/test_performance
