name: Test Performance on GitHub Actions

on: [push]

jobs:
  # General build and test job
  build_and_test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run All Tests with CTest
        run: |
          cd build
          ctest -V

  # Run specific tests or executables
  test_job_template:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        command:
          - ./src/main
          - ./src/test_dataset
          - ./src/test_dataset_with_rejection datasets/data_rejection
          - ./src/test_performance
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Run Specific Test
        run: |
          cd build
          ${{ matrix.command }}
