name: test performance on github actions
on: [push]

jobs:
    test_main:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run main script
            run: g++ src/main.cpp -o /tmp/main; /tmp/main
    test_dataset:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run test script
            run: g++ src/test_dataset.cpp -o /tmp/test_dataset && /tmp/test_dataset

    test_baruch_dataset:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run test script on dataset from Baruch
            run: g++ src/test_dataset.cpp -o /tmp/test_dataset && /tmp/test_dataset datasets/parse_baruch_dataset/data

    test_performance:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: run performance script
            run: g++ src/test_performance.cpp -o /tmp/test_performance && /tmp/test_performance

    test_rejection:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - name: test with rejection
            run: g++ -g src/test_dataset_with_rejection.cpp -o /tmp/test_dataset_with_rejection && /tmp/test_dataset_with_rejection datasets/data_rejection
