name: test performance on github actions
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run main script
              run: g++ main.cpp -o main; ./main
            - name: run test script
              run: g++ test_dataset.cpp -o test_dataset; ./test_dataset
            

